### ISSUE TITLE
missing crepe_eval_model.pyth file

### ISSUE THREAD

**Issue by mteja009** [FabiTheGabi/VideoProcessMining#4]
Hi @FabiTheGabi 
First, thanks for this fantastic code; it is impressive.
I wanted to reproduce your results following the instructions on CREPE_DEMO.dm file, but I can not find the trained model stated in that file: https://www.fim-rc.de/wp-content/uploads/crepe_eval_model.pyth, it seems like the file is not there anymore. Any chance you can provide an alternative URL to download it, please
thanks so much

Manuel Tejada

**Comment by wolfitherolfi** [comment]
Dear Manuel, 

now, the the link you mentioned should work again. Sorry for the inconvenience and thanks for reporting this issue!

Best regards and good luck with your research
Wolfgang
